# Generated by Django 5.0.1 on 2024-03-14 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_mpesapayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesapayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AddField(
            model_name='mpesapayment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 14, 15, 7, 40, 990324)),
        ),
    ]
