# Generated by Django 5.0.1 on 2024-03-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_mpesapayment_amount_mpesapayment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesapayment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
