# Generated by Django 5.0.1 on 2024-03-14 13:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_mpesapayment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesapayment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
