# Generated by Django 5.0.1 on 2024-03-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_application_applicant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Denied', 'Denied')], default='Pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='UserApplication',
        ),
    ]
