# Generated by Django 5.0.1 on 2024-03-12 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_application_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='cover_letter',
            new_name='application_message',
        ),
        migrations.AddField(
            model_name='application',
            name='cv',
            field=models.FileField(default='No CV provided', upload_to='cvs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('pending', 'Pending'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
    ]
