# Generated by Django 5.0.1 on 2024-03-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_application_apply_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='profile_image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
