# Generated by Django 5.0.1 on 2024-03-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_application_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
