# Generated by Django 5.0.1 on 2024-03-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_application_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
