# Generated by Django 5.0.1 on 2024-02-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_subscriptionplan_customuser_subscription_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
