# Generated by Django 5.0.1 on 2024-02-20 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_student_studentskills_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studentskills',
            new_name='Student',
        ),
    ]
