# Generated by Django 4.2.5 on 2024-02-21 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_studentskills_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='fields_of_study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='accounts.fieldofstudy'),
        ),
    ]
