# Generated by Django 4.2.5 on 2024-02-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='skills',
            field=models.ManyToManyField(related_name='users', to='accounts.skill'),
        ),
    ]
