# Generated by Django 4.2.5 on 2024-02-28 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
