# Generated by Django 5.0.1 on 2024-03-10 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_recruiterprofile_studentprofile_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
