# Generated by Django 5.0.1 on 2024-03-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='cv',
            field=models.FileField(blank=True, upload_to='cvs/'),
        ),
    ]
