# Generated by Django 5.0.1 on 2024-03-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_studentprofile_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='subscription_plan',
            field=models.CharField(default='basic', max_length=100),
        ),
    ]
