# Generated by Django 5.0.1 on 2024-03-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_recruiterprofile_subscription_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterprofile',
            name='subscription_plan',
            field=models.CharField(max_length=100),
        ),
    ]
