# Generated by Django 4.2.5 on 2024-02-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internconnect', '0006_internship_expiry_date_internship_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='other_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
