# Generated by Django 4.2.5 on 2024-02-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_skills'),
        ('internconnect', '0007_internship_other_skills_delete_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='skills',
            field=models.ManyToManyField(related_name='internships', to='accounts.skill'),
        ),
    ]
