# Generated by Django 4.2.5 on 2024-02-28 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('internconnect', '0009_remove_internship_other_skills_selectedskill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='recipient',
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
