# Generated by Django 4.2.5 on 2024-02-29 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internconnect', '0011_internship_fields_of_study'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='fields_of_study',
        ),
    ]
