# Generated by Django 5.0.1 on 2024-03-07 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internconnect', '0014_internshipapplication_internship_candidates_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='candidates',
            field=models.ManyToManyField(related_name='applied_internships', through='internconnect.InternshipApplication', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
