# Generated by Django 5.0.1 on 2024-03-07 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internconnect', '0015_alter_internship_candidates_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='candidates',
        ),
        migrations.AddField(
            model_name='internship',
            name='_candidates',
            field=models.ManyToManyField(related_name='applied_internships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='InternshipApplication',
        ),
    ]
