# Generated by Django 5.0.1 on 2024-03-07 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internconnect', '0016_remove_internship_candidates_internship__candidates_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internship',
            old_name='_candidates',
            new_name='candidates',
        ),
    ]
