# Generated by Django 5.0.1 on 2024-03-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internconnect', '0017_rename__candidates_internship_candidates'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='opened',
            field=models.BooleanField(default=False),
        ),
    ]
