# Generated by Django 5.0.1 on 2024-03-10 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internconnect', '0018_notification_opened'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='candidates',
        ),
    ]
