# Generated by Django 5.0.1 on 2024-03-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internconnect', '0019_remove_internship_candidates'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='max_responses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
