# Generated by Django 5.0.1 on 2024-03-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internconnect', '0020_internship_max_responses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='max_responses',
            field=models.PositiveIntegerField(),
        ),
    ]
