# Generated by Django 5.0.1 on 2024-03-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internconnect', '0022_internship_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
